// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                   = new(Query)
	BlacklistedUser     *blacklistedUser
	GameSubscription    *gameSubscription
	Reservation         *reservation
	YoutubeSubscription *youtubeSubscription
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	BlacklistedUser = &Q.BlacklistedUser
	GameSubscription = &Q.GameSubscription
	Reservation = &Q.Reservation
	YoutubeSubscription = &Q.YoutubeSubscription
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                  db,
		BlacklistedUser:     newBlacklistedUser(db, opts...),
		GameSubscription:    newGameSubscription(db, opts...),
		Reservation:         newReservation(db, opts...),
		YoutubeSubscription: newYoutubeSubscription(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	BlacklistedUser     blacklistedUser
	GameSubscription    gameSubscription
	Reservation         reservation
	YoutubeSubscription youtubeSubscription
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		BlacklistedUser:     q.BlacklistedUser.clone(db),
		GameSubscription:    q.GameSubscription.clone(db),
		Reservation:         q.Reservation.clone(db),
		YoutubeSubscription: q.YoutubeSubscription.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		BlacklistedUser:     q.BlacklistedUser.replaceDB(db),
		GameSubscription:    q.GameSubscription.replaceDB(db),
		Reservation:         q.Reservation.replaceDB(db),
		YoutubeSubscription: q.YoutubeSubscription.replaceDB(db),
	}
}

type queryCtx struct {
	BlacklistedUser     IBlacklistedUserDo
	GameSubscription    IGameSubscriptionDo
	Reservation         IReservationDo
	YoutubeSubscription IYoutubeSubscriptionDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		BlacklistedUser:     q.BlacklistedUser.WithContext(ctx),
		GameSubscription:    q.GameSubscription.WithContext(ctx),
		Reservation:         q.Reservation.WithContext(ctx),
		YoutubeSubscription: q.YoutubeSubscription.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
